config/routes.rb
PronosticiR3::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :teams

  resources :rounds

  resources :legs

  resources :games

  resources :champions

  resources :bets
  
  match 'valuta' => "home#valuta", :as => "valuta"
  
  match 'valutato' => "home#valutato", :as => "valutato"
    
  match 'giornata' => "home#giornata", :as => "giornata"
  
  match 'utenti/:id' => "user#show", :as => "mostra_utente"
  
  resources :home do
  	 collection do
  	 	post :create_plus
  	 end
  end
  

  
  root :to => "home#index"

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :game_id, :round_id, :champion_id, :user_id, :bid
  belongs_to :game
  belongs_to :round
  belongs_to :champion
  belongs_to :user
  
  def self.giocate(giornata,utente)
    where("round_id = ? AND user_id = ?", giornata, utente)
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def index
    @bets = Bet.all    
  end

  def show
    @bet = Bet.find(params[:id])
  end

  def new
    @bet = Bet.new
  end

  def create
    @bet = Bet.new(params[:bet])
    if @bet.save
      redirect_to @bet, :notice => "Successfully created bet."
    else
      render :action => 'new'
    end
  end

  def edit
    @bet = Bet.find(params[:id])
  end

  def update
    @bet = Bet.find(params[:id])
    if @bet.update_attributes(params[:bet])
      redirect_to @bet, :notice  => "Successfully updated bet."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy
    redirect_to bets_url, :notice => "Successfully destroyed bet."
  end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for @bet do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </p>
  <p>
    <%= f.label :round_id %><br />
    <%= f.text_field :round_id %>
  </p>
  <p>
    <%= f.label :champion_id %><br />
    <%= f.text_field :champion_id %>
  </p>
  <p>
    <%= f.label :bid %><br />
    <%= f.radio_button :bid, "1" %>  <%= f.radio_button :bid, "2" %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/bets/edit.html.erb
<% title "Edit Bet" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @bet %> |
  <%= link_to "View All", bets_path %>
</p>

app/views/bets/index.html.erb
<% title "Bets" %>

<table>
  <tr>
    <th>Game</th>
    <th>Round</th>
    <th>Champion</th>
    <th>Bid</th>
  </tr>
  <% for bet in @bets %>
    <tr>
      <td><%= bet.game_id %></td>
      <td><%= bet.round_id %></td>
      <td><%= bet.champion_id %></td>
      <td><%= bet.bid %></td>
      <td><%= link_to "Show", bet %></td>
      <td><%= link_to "Edit", edit_bet_path(bet) %></td>
      <td><%= link_to "Destroy", bet, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Bet", new_bet_path %></p>

app/views/bets/new.html.erb
<% title "New Bet" %>

<%= render 'form' %>

<p><%= link_to "Back to List", bets_path %></p>

app/views/bets/show.html.erb
<% title "Bet" %>

<p>
  <strong>Game:</strong>
  <%= @bet.game_id %>
</p>
<p>
  <strong>Round:</strong>
  <%= @bet.round_id %>
</p>
<p>
  <strong>Champion:</strong>
  <%= @bet.champion_id %>
</p>
<p>
  <strong>Bid:</strong>
  <%= @bet.bid %>
</p>

<p>
  <%= link_to "Edit", edit_bet_path(@bet) %> |
  <%= link_to "Destroy", @bet, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", bets_path %>
</p>