config/routes.rb
PronosticiR3::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :teams

  resources :rounds

  resources :legs

  resources :games

  resources :champions

  resources :bets
  
  match 'valuta' => "home#valuta", :as => "valuta"
  
  match 'valutato' => "home#valutato", :as => "valutato"
    
  match 'giornata' => "home#giornata", :as => "giornata"
  
  match 'utenti/:id' => "user#show", :as => "mostra_utente"
  
  resources :home do
  	 collection do
  	 	post :create_plus
  	 end
  end
  

  
  root :to => "home#index"

end

app/models/leg.rb
class Leg < ActiveRecord::Base
  has_many :rounds
end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
  def index
    @legs = Leg.all
  end

  def show
    @leg = Leg.find(params[:id])
  end

  def new
    @leg = Leg.new
  end

  def create
    @leg = Leg.new(params[:leg])
    if @leg.save
      redirect_to @leg, :notice => "Successfully created leg."
    else
      render :action => 'new'
    end
  end

  def edit
    @leg = Leg.find(params[:id])
  end

  def update
    @leg = Leg.find(params[:id])
    if @leg.update_attributes(params[:leg])
      redirect_to @leg, :notice  => "Successfully updated leg."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @leg = Leg.find(params[:id])
    @leg.destroy
    redirect_to legs_url, :notice => "Successfully destroyed leg."
  end
end

app/helpers/legs_helper.rb
module LegsHelper
end

app/views/legs/_form.html.erb
<%= form_for @leg do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/legs/edit.html.erb
<% title "Edit Leg" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @leg %> |
  <%= link_to "View All", legs_path %>
</p>

app/views/legs/index.html.erb
<% title "Legs" %>

<table>
  <tr>
    <th>Desc</th>
  </tr>
  <% for leg in @legs %>
    <tr>
      <td><%= leg.desc %></td>
      <td><%= link_to "Show", leg %></td>
      <td><%= link_to "Edit", edit_leg_path(leg) %></td>
      <td><%= link_to "Destroy", leg, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Leg", new_leg_path %></p>

app/views/legs/new.html.erb
<% title "New Leg" %>

<%= render 'form' %>

<p><%= link_to "Back to List", legs_path %></p>

app/views/legs/show.html.erb
<% title "Leg" %>

<p>
  <strong>Desc:</strong>
  <%= @leg.desc %>
</p>

<p>
  <%= link_to "Edit", edit_leg_path(@leg) %> |
  <%= link_to "Destroy", @leg, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", legs_path %>
</p>