config/routes.rb
PronosticiR3::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :teams

  resources :rounds

  resources :legs

  resources :games

  resources :champions

  resources :bets
  
  match 'valuta' => "home#valuta", :as => "valuta"
  
  match 'valutato' => "home#valutato", :as => "valutato"
    
  match 'giornata' => "home#giornata", :as => "giornata"
  
  match 'utenti/:id' => "user#show", :as => "mostra_utente"
  
  resources :home do
  	 collection do
  	 	post :create_plus
  	 end
  end
  

  
  root :to => "home#index"

end

app/models/champion.rb
class Champion < ActiveRecord::Base
  attr_accessible :nome_campionato, :priority, :ambito
  has_many :rounds
  has_many :scores
  has_many :users, :through => :scores
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = Champion.all
  end

  def show
    @champion = Champion.find(params[:id])
  end

  def new
    @champion = Champion.new
  end

  def create
    @champion = Champion.new(params[:champion])
    if @champion.save
      redirect_to @champion, :notice => "Successfully created champion."
    else
      render :action => 'new'
    end
  end

  def edit
    @champion = Champion.find(params[:id])
  end

  def update
    @champion = Champion.find(params[:id])
    if @champion.update_attributes(params[:champion])
      redirect_to @champion, :notice  => "Successfully updated champion."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @champion = Champion.find(params[:id])
    @champion.destroy
    redirect_to champions_url, :notice => "Successfully destroyed champion."
  end
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/views/champions/_form.html.erb
<%= form_for @champion do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :nome_campionato %><br />
    <%= f.text_field :nome_campionato %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </p>
  <p>
    <%= f.label :ambito %><br />
    <%= f.text_field :ambito %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/champions/edit.html.erb
<% title "Edit Champion" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @champion %> |
  <%= link_to "View All", champions_path %>
</p>

app/views/champions/index.html.erb
<% title "Champions" %>

<table>
  <tr>
    <th>Nome Campionato</th>
    <th>Priority</th>
    <th>Ambito</th>
  </tr>
  <% for champion in @champions %>
    <tr>
      <td><%= champion.nome_campionato %></td>
      <td><%= champion.priority %></td>
      <td><%= champion.ambito %></td>
      <td><%= link_to "Show", champion %></td>
      <td><%= link_to "Edit", edit_champion_path(champion) %></td>
      <td><%= link_to "Destroy", champion, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Champion", new_champion_path %></p>

app/views/champions/new.html.erb
<% title "New Champion" %>

<%= render 'form' %>

<p><%= link_to "Back to List", champions_path %></p>

app/views/champions/show.html.erb
<% title "Champion" %>

<p>
  <strong>Nome Campionato:</strong>
  <%= @champion.nome_campionato %>
</p>
<p>
  <strong>Priority:</strong>
  <%= @champion.priority %>
</p>
<p>
  <strong>Ambito:</strong>
  <%= @champion.ambito %>
</p>

<p>
  <%= link_to "Edit", edit_champion_path(@champion) %> |
  <%= link_to "Destroy", @champion, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", champions_path %>
</p>